### ISSUE TITLE
Error while doing check: The process '/usr/bin/curl' failed with exit code 22

### ISSUE THREAD

**Issue by dantebarba** [Jtalk/url-health-check-action#18]
Hello

I'm struggling to make this action work. I tried to set up a healthcheck with 3 retry attemps each of them with a delay of 120s (2m). Unfortunately curl its failing on the first try. I'm attaching the output and also my config:

```
Checking *******
/usr/bin/curl --fail -sv --retry 3 --retry-delay 120 --retry-connrefused -L *******
*   Trying *******..
* TCP_NODELAY set
* Connected to ******* (*********) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
*** [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*** [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
*** [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
*** [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
*** [2332 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify ([15]
*** [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished ([20]
*** [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
*** [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
*** [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jun  7 00:00:00 20[22]
*  expire date: Jun  7 [23]
*  subjectAltName: host "*******" matched cert's "*******"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
*** [5 bytes data]
* Using Stream ID: 1 (easy handle 0x5574883878c0)
*** [5 bytes data]
 GET / HTTP/2
 *******
 user-agent: curl/7.68.0
 accept: */*
 
*** [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
*** [230 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
*** [230 bytes data]
* old SSL session ID is stale, removing
*** [5 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS == [25]
*** [5 bytes data]
 * The requested URL returned error: 522 
 * stopped the pause stream!
* Connection #0 to host ******* left intact
Error: Error: The process '/usr/bin/curl' failed with exit code 22

```
My config:

```yml
    - name: Verify
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: ********
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: true # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 2m # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"
```
