### ISSUE TITLE
Curl command fails without retrying

### ISSUE THREAD

**Issue by wbobeirne** [Jtalk/url-health-check-action#5]
Here's my step:
```yml
      - name: Wait for backend
        id: wait_backend
        uses: jtalk/url-health-check-action@v1.4
        with:
          url: # my url here
          max-attempts: 10
          retry-delay: 30s
```

But I get this immediately when the step runs

```
Error running action Error: Command failed: curl --fail -sv  [my-url] --retry 10 --retry-delay 30 --retry-connrefused
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at curl (/home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:73:20)
    at /home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:90:9
    at Array.forEach (<anonymous>)
Error: Command failed: curl --fail -sv  [my-url] --retry 10 --retry-delay 30 --retry-connrefused
    at Object.34 (/home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:89:10)
    at __webpack_require__ (/home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:37:19)
    at /home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/jtalk/url-health-check-action/v1.4/dist/index.js:44:10) {
  status: 22,
  signal: null,
  output: [ null, null, null ],
  pid: 3005,
  stdout: null,
  stderr: null
}
```

I expected retry to work even on 4XX and 5XX, not just connection refused. Was this an incorrect assumption?
