### ISSUE TITLE
Snippet in Github Actions Marketplace is wrong

### ISSUE THREAD

**Issue by MarekLani** [Jtalk/url-health-check-action#8]
Bellow stated snippet on Github Actions Marketplace also Readme uses wrong values for retry-all and follow-redirects. Using proposed values yes, no results in following error: 

Error: TypeError: Input does not meet YAML 1.2 "Core Schema" specification: follow-redirect
Support boolean input list: `true | True | TRUE | false | False | FALSE`

Solution: docs should use true | True | TRUE | false | False | FALSE

```
steps:
  - name: Check the deployed service URL
    uses: jtalk/url-health-check-action@v2
    with:
      # Check the following URLs one by one sequentially
      url: https://example.com|http://example.com
      # Follow redirects, or just report success on 3xx status codes
      follow-redirect: no # Optional, defaults to "no"
      # Fail this action after this many failed attempts
      max-attempts: 3 # Optional, defaults to 1
      # Delay between retries
      retry-delay: 5s # Optional, only applicable to max-attempts > 1
      # Retry all errors, including 404. This option might trigger curl upgrade.
      retry-all: no # Optional, defaults to "no"
```
